# Generated by Django 5.1.6 on 2025-02-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the article.', max_length=255)),
                ('content', models.TextField(help_text='The full content of the article.')),
                ('url', models.URLField(help_text='The original URL of the article.', unique=True)),
                ('published_date', models.DateTimeField(help_text='The date and time when the article was published.')),
                ('source', models.CharField(help_text='The source of the article.', max_length=100)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
