# Generated by Django 5.2.3 on 2025-07-09 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, help_text='The author of the article.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the article was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description or summary of the article.', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='An optional image URL for the article.', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='news_client_source',
            field=models.CharField(default='NewsAPI', help_text='The news client source of the article.', max_length=100),
            preserve_default=False,
        ),
    ]
