# Generated by Django 5.2.4 on 2025-07-09 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_author_article_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, help_text='The AI-generated summary text', null=True)),
                ('ai_model', models.CharField(default='openai-gpt-4.1-nano', help_text='The AI model used for summarization', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the summarization', max_length=20)),
                ('word_count', models.IntegerField(blank=True, help_text='Number of words in the summary', null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used by the AI model', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if summarization failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the summary request was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the summary was completed', null=True)),
                ('article', models.ForeignKey(help_text='The article being summarized', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='articles.article')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who requested the summary', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'ai_model')},
            },
        ),
    ]
