# Generated by Django 5.2.4 on 2025-07-09 16:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsClientFetcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the news source', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is active')),
                ('class_path', models.CharField(help_text="Python import path to the client class (e.g., 'clients.newsapi.NewsApiClient')", max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Configuration parameters for the fetcher')),
                ('fetch_interval', models.IntegerField(default=6, help_text='Hours between fetch operations')),
                ('last_fetch', models.DateTimeField(blank=True, help_text='When the last fetch was performed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING', help_text='Current status of the fetch operation', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the fetch operation started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the fetch operation completed', null=True)),
                ('articles_fetched', models.IntegerField(default=0, help_text='Number of articles fetched from the source')),
                ('articles_saved', models.IntegerField(default=0, help_text='Number of articles successfully saved')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the fetch operation failed')),
                ('query_params', models.JSONField(default=dict, help_text='Parameters used for the fetch operation')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata about the fetch operation')),
                ('raw_data_file', models.CharField(blank=True, help_text='Path to the raw JSON data file', max_length=255)),
                ('source', models.ForeignKey(blank=True, help_text='The news source used for this fetch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fetch_logs', to='fetchers.newsclientfetcher')),
            ],
            options={
                'verbose_name': 'Fetch Log',
                'verbose_name_plural': 'Fetch Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='fetchers_fe_status_851d97_idx')],
            },
        ),
    ]
