# Generated by Django 5.2.4 on 2025-07-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchlog',
            name='source',
            field=models.CharField(help_text='The api source used for this fetch', max_length=100),
        ),
        migrations.DeleteModel(
            name='NewsClientFetcher',
        ),
    ]
