# Generated by Django 5.2.4 on 2025-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchers', '0002_alter_fetchlog_source_delete_newsclientfetcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchlog',
            name='source',
            field=models.CharField(blank=True, help_text='The api source used for this fetch', max_length=100, null=True),
        ),
    ]
